services:
  - type: web
    name: n8n-yt-automation
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false

